name: accrete
favicon: null
layout_spectrum: 1
typography_spectrum: 0.3359920976217836
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.5564053673297167
  lightness: 0.12664721999317408
  saturation: 0.11429688078351319
  rhythmicContrast: 0.42596724606119096
purpose: []
