name: accrete
favicon: null
layout_spectrum: 1
typography_spectrum: 0.3359920976217836
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#282828'
    - '#71a2dd'
    - '#cde5fd'
    - '#bc9a94'
    - '#fbba9f'
  brandStrength: 0.5
  lightness: 0.12664721999317408
  saturation: 0.1875
  rhythmicContrast: 0.42596724606119096
purpose: []
